name: ogireal_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"
version: 1.0.2+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.29.0
  firebase_messaging: ^14.8.1
  google_api_availability: ^5.0.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  freezed: ^2.5.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  cloud_firestore: ^4.16.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.1.1
  google_mobile_ads: ^5.1.0
  table_calendar: ^3.1.1
  rate_my_app: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

#  追加
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpg"
